### PR TITLE
MAUI template app

### PR DESCRIPTION
**Pull request by papafe**
The code is ready for review, but there is a strange behaviour with sync due to https://github.com/realm/realm-dotnet/issues/3128. This can cause some error loops on iOS in some specific situations

### CODE REVIEW

**Comment by thompsch** [comment]
Initial build fails: "Error: No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from https://developer.apple.com."

We need to make sure the app works "out of the box".

**Comment by thompsch** [comment]
App crashes while subscribing:
image

**Comment by thompsch** [comment]
When adding a new task, we get:
`Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{b4990ca position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} crc645d80431ce5f73f11.MauiRecyclerView_3{6cdf817 VFED..... ......ID 0,165-1080,1631}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@da229d2, layout:androidx.recyclerview.widget.LinearLayoutManager@ac71507, context:crc6445a4ae5df7ce5659.MainActivity@abe2777`

**Comment by thompsch** [comment]
Log out and log back in and you get:
`Realm at path '/data/user/0/com.companyname.realmtodo/files/mongodb-realm/todo-template-tldrx/6397604aba203e7c694f4a5a/default.realm' already opened with different sync user.`

**Comment by papafe** [comment]
> iOS build fails: "Error: No valid iOS code signing keys found in keychain. You need to request a codesigning certificate from [developer.apple.com](https://developer.apple.com)."
> 
> We need to make sure the app works "out of the box".

Is this happening on build or on run? I've seen this happening on build, but not when trying to run the app. This seems to be an issue with MAUI

**Comment by papafe** [comment]
> When adding a new task, we get: `Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{b4990ca position=1 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} crc645d80431ce5f73f11.MauiRecyclerView_3{6cdf817 VFED..... ......ID 0,165-1080,1631}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@da229d2, layout:androidx.recyclerview.widget.LinearLayoutManager@ac71507, context:crc6445a4ae5df7ce5659.MainActivity@abe2777`

Is this causing a crash or is it an error that is appearing in the logs? I can try to investigate a little but I'm not sure I can do much about it. Unfortunately MAUI it's quite buggy, and it seems that the main sufferer is Android unfortunately

**Comment by papafe** [comment]
> Log out and log back in and you get: `Realm at path '/data/user/0/com.companyname.realmtodo/files/mongodb-realm/todo-template-tldrx/6397604aba203e7c694f4a5a/default.realm' already opened with different sync user.`

I found the reason for this.... The more I use MAUI and more I want to go back to Xamarin.Forms. The issue here is that pages are reused (including view model) and it's not possible to change this behaviour. This means that the page was keeping a reference to the `realm` that could not be garbage collected and this exception is the result. Now I'm disposing of the realm manually before logging out. I also had another issue with this, but it seems to be fixed too.

**Comment by papafe** [comment]
> App crashes while subscribing to "all": image

Can you reproduce this? I didn't manage to see this.

**Comment by papafe** [comment]
@cbush @thompsch This should be ready for review. I didn't manage to reproduce the "subscription store" error, but let me know if it happens again.

**Review by cbush — APPROVED** [review]
Thanks!

**Comment by MongoCaleb** [comment]
@papafe When I add a new item, the app is throwing the following: 

```
Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{44bddc2 position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} crc645d80431ce5f73f11.MauiRecyclerView_3{c107422 VFED..... ......ID 0,165-1080,1631}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@cebf159, layout:androidx.recyclerview.widget.LinearLayoutManager@da229d2, context:crc6445a4ae5df7ce5659.MainActivity@6e5dc4d

   at Java.Interop.JniEnvironment.StaticMethods.CallStaticLongMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 13131
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeInt64Method(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 133
   at Microsoft.Maui.PlatformInterop.MeasureAndGetWidthAndHeight(View view, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in D:\a\_work\1\s\src\Core\src\obj\Release\net7.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 504
   at Microsoft.Maui.ViewHandlerExtensions.GetDesiredSizeFromHandler(IViewHandler viewHandler, Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Core\src\Handlers\ViewHandlerExtensions.Android.cs:line 91
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[AndroidX.RecyclerView.Widget.RecyclerView, Xamarin.AndroidX.RecyclerView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetDesiredSize(Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.Android.cs:line 18
   at Microsoft.Maui.Layouts.LayoutExtensions.ComputeDesiredSize(IView view, Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:line 27
   at Microsoft.Maui.Controls.VisualElement.MeasureOverride(Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 149
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Measure(Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 142
   at Microsoft.Maui.Layouts.GridLayoutManager.GridStructure.MeasureCellsWithUnknowns() in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 349
   at Microsoft.Maui.Layouts.GridLayoutManager.GridStructure.MeasureCells() in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 319
   at Microsoft.Maui.Layouts.GridLayoutManager.GridStructure..ctor(IGridLayout grid, Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 134
   at Microsoft.Maui.Layouts.GridLayoutManager.Measure(Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 22
   at Microsoft.Maui.Controls.Layout.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 282
   at Microsoft.Maui.Platform.LayoutViewGroup.OnMeasure(Int32 widthMeasureSpec, Int32 heightMeasureSpec) in D:\a\_work\1\s\src\Core\src\Platform\Android\LayoutViewGroup.cs:line 67
   at Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 18941
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 154
  --- End of managed Java.Lang.IndexOutOfBoundsException stack trace ---
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{44bddc2 position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} crc645d80431ce5f73f11.MauiRecyclerView_3{c107422 VFED..... ......ID 0,165-1080,1631}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@cebf159, layout:androidx.recyclerview.widget.LinearLayoutManager@da229d2, context:crc6445a4ae5df7ce5659.MainActivity@6e5dc4d
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3680)
	at android.view.View.measure(View.java:25773)
	at com.microsoft.maui.PlatformInterop.measureAndGetWidthAndHeight(PlatformInterop.java:322)
	at crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onMeasure(Native Method)
	at crc6452ffdc5b34af3a0f.LayoutViewGroup.onMeasure(LayoutViewGroup.java:59)
	at android.view.View.measure(View.java:25773)
	at com.microsoft.maui.PlatformInterop.measureAndGetWidthAndHeight(PlatformInterop.java:322)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onMeasure(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.onMeasure(ContentViewGroup.java:67)
	at android.view.View.measure(View.java:25773)
	at crc640ec207abc449b2ca.ShellPageContainer.n_onMeasure(Native Method)
	at crc640ec207abc449b2ca.ShellPageContainer.onMeasure(ShellPageContainer.java:66)
	at android.view.View.measure(View.java:25773)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25773)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9681)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1657)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2253)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
	at android.view.View.layout(View.java:23143)
	at android.view.ViewGroup.layout(ViewGroup.java:6412)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3684)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Review by MongoCaleb — APPROVED** [review]
LGTM

**Pull request merged**
